### ISSUE TITLE
Dynamically scale with window resize

### ISSUE THREAD

**Issue by hp7** [Taitava/silverstripe-slickcarousel#4]
Is there anyway to set the image to dynamically scale, when the browser window is resized? The normal way setting width=100% height=auto does not work since your code is taking the image width and setting a fixed width to the slide container. Setting responsive break points is not good enough when using elastic designs. I noticed the slick demo site actually does do what I am asking about. Thanks for the great extension, any input would be great

**Comment by Taitava** [comment]
Thanks for your question! :)

I think the module should not set any fixed width or height unless you have explicitly configured it to do so. This default configuration should prevent the module from defining a fixed width:

```YAML
Carousel:
  use_image_dimensions: false
```
If you already have set that option to false and it still defines fixed dimensions for the containers, it must be a bug. Please let me know if there's a bug and I will fix it.

Whether it's a bug or not, another way that might help a little bit - although this is not so convenient - is that you could copy `CarouselSlide.ss` to `themes/*your-theme-name*/templates` and modify it so that it doesn't use `$StyleAttribute` to define inline CSS styles for the container. 

Please remember to run `?flush=all` after any change to the configuration and/or after creating a new template file.

Does any of this help you?

**Comment by hp7** [comment]
I had a typo in the following. Thanks!
Carousel:
  use_image_dimensions: false
